"use client";

import { useEffect, useState } from "react";
import { ShieldAlert, ShieldCheck, Users } from "lucide-react";
type User = { id: string; email: string; plan: string; usageCount: number; isSuspended: boolean; createdAt: string };

export default function AdminPage() {
  const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true);
  const fetchUsers = async () => { try { const res = await fetch("/api/admin/users"); if (!res.ok) throw new Error("Unable to load users"); setUsers(await res.json()); } catch (err) { console.error(err); } finally { setLoading(false); } };
  useEffect(() => { void fetchUsers(); }, []);
  const updateUser = async (id: string, updates: Partial<User>) => { try { const res = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...updates }) }); if (!res.ok) throw new Error("Unable to update user"); void fetchUsers(); } catch (err) { console.error(err); } };
  if (loading) return <div className="grid min-h-48 place-items-center text-sm text-text-muted">Loading users…</div>;
  return <div className="mx-auto max-w-6xl"><header className="mb-6 flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent-light text-accent"><Users size={21} /></span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-accent">Administration</p><h1 className="mt-1 font-outfit text-3xl font-bold tracking-[-0.03em] text-text">People and plans</h1><p className="mt-1 text-sm text-text-muted">Manage account status and plan access.</p></div></header><div className="overflow-x-auto rounded-2xl border border-border bg-panel shadow-[0_4px_16px_rgba(30,41,59,0.025)]"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border bg-panel-alt text-xs font-bold uppercase tracking-wide text-text-muted"><th className="p-4">Email</th><th className="p-4">Plan</th><th className="p-4">Usage</th><th className="p-4">Status</th><th className="p-4">Joined</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-border">{users.length === 0 ? <tr><td colSpan={6} className="p-10 text-center text-text-muted">No users found yet.</td></tr> : users.map((user) => <tr key={user.id} className="text-text-muted transition hover:bg-panel-alt"><td className="p-4 font-medium text-text">{user.email}</td><td className="p-4"><select value={user.plan} onChange={(e) => void updateUser(user.id, { plan: e.target.value })} className="h-9 rounded-lg border border-border bg-panel px-2 text-xs font-bold text-text-muted outline-none focus:border-accent"><option value="FREE">FREE</option><option value="PRO">PRO</option><option value="AGENCY">AGENCY</option></select></td><td className="p-4">{user.usageCount} imports</td><td className="p-4">{user.isSuspended ? <span className="inline-flex items-center gap-1.5 rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-600"><ShieldAlert size={14} />Suspended</span> : <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-600"><ShieldCheck size={14} />Active</span>}</td><td className="p-4 text-text-muted">{new Date(user.createdAt).toLocaleDateString()}</td><td className="p-4"><button onClick={() => void updateUser(user.id, { isSuspended: !user.isSuspended })} className="cursor-pointer rounded-lg px-2 py-1 text-xs font-semibold text-text-muted transition hover:bg-accent-light hover:text-accent">{user.isSuspended ? "Unsuspend" : "Suspend"}</button></td></tr>)}</tbody></table></div></div>;
}
