"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Check, ChevronLeft, Cloud, Layers3, LifeBuoy, LockKeyhole, PenSquare, Plus, Sparkles, Trash2 } from "lucide-react";

type Account = { email: string; plan: "FREE" | "PRO" | "AGENCY"; usage: { used: number; limit: number | null; periodStart: string }; features: { cloudSync: boolean; teamWorkspaces: boolean; customVoices: boolean } };
type Workspace = { id: string; name: string; isPersonal: boolean };
type Voice = { id: string; name: string; instructions: string };

async function requestJson<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); if (!response.ok) { const body: unknown = await response.json().catch(() => null); throw new Error(body && typeof body === "object" && "error" in body && typeof body.error === "string" ? body.error : "Request failed"); } return response.status === 204 ? (undefined as T) : response.json() as Promise<T>; }
const fieldClass = "min-h-11 w-full rounded-xl border border-border bg-panel-alt px-3 text-sm text-text outline-none transition placeholder:text-text-muted focus:bg-panel";

export default function SettingsClient() {
  const [account, setAccount] = useState<Account | null>(null); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [voices, setVoices] = useState<Voice[]>([]); const [notice, setNotice] = useState("");
  const [workspaceName, setWorkspaceName] = useState(""); const [memberWorkspaceId, setMemberWorkspaceId] = useState(""); const [memberEmail, setMemberEmail] = useState(""); const [voiceName, setVoiceName] = useState(""); const [voiceInstructions, setVoiceInstructions] = useState(""); const [supportSubject, setSupportSubject] = useState(""); const [supportMessage, setSupportMessage] = useState("");
  const load = async () => { try { const next = await requestJson<Account>("/api/account"); setAccount(next); if (next.features.cloudSync || next.features.teamWorkspaces) setWorkspaces(await requestJson<Workspace[]>("/api/workspaces")); if (next.features.customVoices) setVoices(await requestJson<Voice[]>("/api/agency/voice-presets")); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load account settings"); } };
  useEffect(() => { void load(); }, []);
  const submitWorkspace = async (event: FormEvent) => { event.preventDefault(); try { await requestJson("/api/workspaces", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: workspaceName }) }); setWorkspaceName(""); setNotice("Workspace created."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to create workspace"); } };
  const submitMember = async (event: FormEvent) => { event.preventDefault(); try { await requestJson(`/api/workspaces/${memberWorkspaceId}/members`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: memberEmail }) }); setMemberEmail(""); setNotice("Team member added."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to add member"); } };
  const submitVoice = async (event: FormEvent) => { event.preventDefault(); try { await requestJson("/api/agency/voice-presets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: voiceName, instructions: voiceInstructions }) }); setVoiceName(""); setVoiceInstructions(""); setNotice("Voice preset saved."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save voice preset"); } };
  const removeVoice = async (id: string) => { try { await requestJson("/api/agency/voice-presets", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); setNotice("Voice preset deleted."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to delete voice preset"); } };
  const submitSupport = async (event: FormEvent) => { event.preventDefault(); try { await requestJson("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject: supportSubject, message: supportMessage }) }); setSupportSubject(""); setSupportMessage(""); setNotice("Support request submitted. We will follow up through your account email."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to send support request"); } };
  const agency = account?.plan === "AGENCY"; const limitLabel = account?.usage.limit === null ? "Unlimited" : `${account?.usage.used ?? 0} / ${account?.usage.limit ?? 0}`;
  return <main className="min-h-screen bg-surface px-4 py-5 text-text sm:px-8 sm:py-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center justify-between"><Link href="/editor" className="flex items-center gap-2.5 font-outfit text-lg font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-accent text-white"><PenSquare size={18} /></span>GemmaNote</Link><Link href="/editor" className="inline-flex min-h-10 items-center gap-1.5 rounded-xl px-3 text-sm font-semibold text-text-muted transition hover:bg-panel hover:text-accent"><ChevronLeft size={17} />Workspace</Link></header>
    <section className="grid gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-3xl border border-border bg-panel p-7 shadow-[0_8px_28px_rgba(30,41,59,0.035)] sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.18em] text-accent">Account settings</p><h1 className="mt-3 max-w-xl font-outfit text-4xl font-bold tracking-[-0.04em] text-text sm:text-5xl">Your workspace, on your terms.</h1><p className="mt-4 max-w-2xl leading-7 text-text-muted">Manage sync, team tools, reusable voices, and get help without leaving the GemmaNote writing system.</p><p className="mt-7 text-sm font-medium text-text-muted">Signed in as <span className="text-text">{account?.email ?? "Loading…"}</span></p></div><aside className="rounded-3xl bg-accent p-7 text-white shadow-[0_12px_28px_rgba(99,102,241,0.2)]"><p className="text-xs font-bold uppercase tracking-[0.18em] opacity-80">Current plan</p><p className="mt-3 font-outfit text-4xl font-bold">{account?.plan ?? "Loading"}</p><div className="mt-8 border-t border-white/20 pt-4"><p className="text-sm opacity-80">This month&apos;s imports</p><p className="mt-1 font-outfit text-2xl font-bold">{limitLabel}</p></div></aside></section>
    {notice && <div role="status" className="mt-5 flex items-center gap-2 rounded-xl border border-accent-light bg-accent-light px-4 py-3 text-sm text-accent"><Check size={16} />{notice}</div>}
    <section className="mt-5 grid gap-4 md:grid-cols-3"><FeatureCard icon={<Cloud size={20} />} title="Cloud sync" active={Boolean(account?.features.cloudSync)} copy={account?.features.cloudSync ? "Your notes have a server-backed copy." : "Available with Pro and Agency."} /><FeatureCard icon={<Layers3 size={20} />} title="Workspaces" active={agency} copy={agency ? "Create spaces for clients and teams." : "Available with the Agency plan."} /><FeatureCard icon={<Sparkles size={20} />} title="Voice presets" active={Boolean(account?.features.customVoices)} copy={account?.features.customVoices ? "Reusable writing rules for your team." : "Available with the Agency plan."} /></section>
    {agency ? <section className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="Workspaces" icon={<Layers3 size={18} />}><form onSubmit={submitWorkspace} className="flex gap-2"><input required value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} placeholder="New client workspace" className={fieldClass} /><button className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-accent text-white transition hover:bg-accent-hover" aria-label="Create workspace"><Plus size={18} /></button></form><div className="mt-4 space-y-2">{workspaces.map((workspace) => <div key={workspace.id} className="flex items-center justify-between rounded-xl border border-border px-3.5 py-3 text-sm"><span className="font-medium text-text">{workspace.name}</span><span className="text-xs text-text-muted">{workspace.isPersonal ? "Personal" : "Team"}</span></div>)}</div><form onSubmit={submitMember} className="mt-5 grid gap-2 border-t border-border pt-5"><select required value={memberWorkspaceId} onChange={(event) => setMemberWorkspaceId(event.target.value)} className={fieldClass}><option value="">Choose a workspace</option>{workspaces.filter((workspace) => !workspace.isPersonal).map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select><div className="flex gap-2"><input required type="email" value={memberEmail} onChange={(event) => setMemberEmail(event.target.value)} placeholder="Existing member email" className={fieldClass} /><button disabled={!memberWorkspaceId} className="min-h-11 rounded-xl bg-accent-light px-4 text-sm font-semibold text-accent transition hover:opacity-80 disabled:cursor-not-allowed disabled:opacity-50">Add</button></div></form></Panel>
      <Panel title="Voice presets" icon={<Sparkles size={18} />}><form onSubmit={submitVoice} className="space-y-2"><input required value={voiceName} onChange={(event) => setVoiceName(event.target.value)} placeholder="Voice name" className={fieldClass} /><textarea required value={voiceInstructions} onChange={(event) => setVoiceInstructions(event.target.value)} placeholder="Tone, vocabulary, point of view, and writing rules…" className={`${fieldClass} min-h-28 py-3`} /><button className="min-h-11 rounded-xl bg-accent px-4 text-sm font-semibold text-white transition hover:bg-accent-hover">Save voice</button></form><div className="mt-4 space-y-2">{voices.map((voice) => <div key={voice.id} className="flex items-center justify-between gap-3 rounded-xl border border-border px-3.5 py-3"><div className="min-w-0"><p className="text-sm font-medium text-text">{voice.name}</p><p className="truncate text-xs text-text-muted">{voice.instructions}</p></div><button onClick={() => void removeVoice(voice.id)} className="cursor-pointer rounded-lg p-1.5 text-text-muted transition hover:bg-red-50 hover:text-red-500" aria-label={`Delete ${voice.name}`}><Trash2 size={16} /></button></div>)}</div></Panel></section> : <section className="mt-5 rounded-2xl border border-border bg-panel p-6 shadow-[0_4px_16px_rgba(30,41,59,0.025)] sm:p-7"><div className="flex items-start gap-4"><span className="rounded-xl bg-panel-alt p-3 text-text-muted"><LockKeyhole size={20} /></span><div><h2 className="font-outfit text-2xl font-bold">Agency tools are ready when you are.</h2><p className="mt-2 max-w-2xl leading-7 text-text-muted">Upgrade when you need client workspaces or reusable voice systems. Pro adds cloud sync without the Agency controls.</p></div></div></section>}
    <section className="mt-5 rounded-2xl border border-border bg-panel p-6 shadow-[0_4px_16px_rgba(30,41,59,0.025)] sm:p-7"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-accent-light p-2.5 text-accent"><LifeBuoy size={19} /></span><div><h2 className="font-outfit text-2xl font-bold">Support desk</h2><p className="text-sm text-text-muted">Send a request and we will reply to your account email.</p></div></div><form onSubmit={submitSupport} className="grid gap-3"><input required value={supportSubject} onChange={(event) => setSupportSubject(event.target.value)} placeholder="What can we help with?" className={fieldClass} /><textarea required value={supportMessage} onChange={(event) => setSupportMessage(event.target.value)} placeholder="Give us the detail we need to help…" className={`${fieldClass} min-h-28 py-3`} /><button className="min-h-11 w-fit rounded-xl bg-accent px-4 text-sm font-semibold text-white transition hover:bg-accent-hover">Send request</button></form></section>
  </div></main>;
}
function FeatureCard({ icon, title, active, copy }: { icon: React.ReactNode; title: string; active: boolean; copy: string }) { return <article className="rounded-2xl border border-border bg-panel p-5 shadow-[0_4px_16px_rgba(30,41,59,0.025)]"><div className={`mb-5 inline-flex rounded-xl p-2.5 ${active ? "bg-accent-light text-accent" : "bg-panel-alt text-text-muted"}`}>{icon}</div><div className="flex items-center gap-2"><h2 className="font-outfit text-xl font-bold">{title}</h2><span className={`h-2 w-2 rounded-full ${active ? "bg-emerald-400" : "bg-slate-300"}`} /></div><p className="mt-2 text-sm leading-6 text-text-muted">{copy}</p></article>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-panel p-6 shadow-[0_4px_16px_rgba(30,41,59,0.025)]"><div className="mb-5 flex items-center gap-2 text-accent">{icon}<h2 className="font-outfit text-xl font-bold text-text">{title}</h2></div>{children}</section>; }
